name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag react-app
      - name: deploy Docker image
        run: |
          docker ps -q --filter  "expose=3000" | xargs -r docker stop
          docker run -d --network bridge -p 3000:3000 react-app:latest
        shell: bash
